[package]
name = "Fluid-Simulation-Component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"

[[bin]]
name = "Fluid-Simulation-Component"
path = "main.rs"
